### ISSUE TITLE
Expense Management

### ISSUE THREAD

**Issue by Frecherenkel60** [aaronschweig/wwi21seb#1]
## Projektidee

Die Idee ist es ein Tool zu erstellen, welches bei der Erfassung und gerechten Verteilung der entstehenden Kosten bei einer Reise unterstützen soll. Das Tool soll bereits dieses Jahr eingesetzt werden, wenn einige von uns gemeinsam ein Auslandssemester durchführen. :)

Die Entwicklung beinhaltet ein in Svelte (TS) geschriebenes UI und ein in Golang geschriebenes Backend. Die Wahl der Datenbank steht noch aus.

**Geplante Features**

*Technische Features*

- [x] Authentication
- [x] Datenbank
- [x] Server Side Rendering
- [x] Backend
- [x] CI/CD-Pipelines
- [x] Anwendungen in Docker-Containern deployen

*Wirtschaftliche Features*

- [x] Erstellung von Reisegruppen und dem Hinzufügen von Teilnehmern zu der Reisegruppe
- [x] Erstellung von Kostengruppen innerhalb einer Reisegruppe (bspw. Tankkosten, Lebensmittelkosten ...) und dem Hinzufügen von Teilnehmern zu der Kostengruppe
- [x] Erfassung von Kosten in einer Kostengruppe und Angabe von zahlender Person + Verteilungsmethode (gleichmäßig, prozentual unterschiedlich, anteilmäßig unterschiedlich)
- [x] Übersicht aller ausstehenden Kosten pro Kostengruppe oder Reisegruppe

## Gruppenmitglieder (5-6 Studierende)

* @Frecherenkel60
* @930C
* @johannadke
* @zimmerai
* @lisaress

## (Optional) Mockups

Werden irgendwann morgen eingefügt

## (Optional) Sonstiges

Die beteiligten Repositories sind öffentlich geführt unter folgender Org: [Travel Utilities WWI21SEB](https://github.com/Travel-Utilities-WWI21SEB)

**Comment by aaronschweig** [comment]
Hallo,
danke schonmal für das Einreichen euerer Projektidee! Die Idee find ich klasse und auch die Technologiewahl finde ich richtig gut. Eine Frage hätte ich aber noch:

Ich habe in eurer Org gesehen, dass ihr ein SvelteKit repo für die UI und ein separates backend repo habt. Mit SvelteKit habt ihr ja aber ein sehr gutes SSR fähiges Framework, was bedeutet, dass auch dort Backend code geschrieben werden könnte. Hat es einen bestimmten Grund, wieso ihr ein separated Backend in Go schreiben wollt? Ich finde das natürlich super - meine Lieblingsprogrammiersprache - aber es würde mich interessieren, was eure Idee hinter der Trennung war?

**Comment by Frecherenkel60** [comment]
Hey,

berechtigte Frage. Wir wollten in unserer Architektur einen klareren Cut zwischen Front- und Backend, weil wir in Zukunft eventuell in unserer Freizeit auch mal eine mobile App hiervon entwickelten wollten und es einfacher wäre mit einem bereits bestehenden Backend. SvelteKit wollten wir trotzdem benutzen aufgrund der coolen Features wie das Routing, Layouts, dem integrierten Store etc.

Aber auch so wollten wir einfach mal bisschen tiefer in Golang rein und dachten, dass sich das Projekt hierfür gut anbietet. Soweit ich jetzt recherchiert habe, sollten Aspekte wie SSR durch ein separates Backend ja nicht verloren gehen, wir müssten es nur an unsere Backend-Domäne weiterleiten.

**Comment by aaronschweig** [comment]
Fair enough - noch ein kleiner Link zur Doku bzgl. [API-Routes](https://learn.svelte.dev/tutorial/get-handlers) just in case - aber ihr dürft gerne Go exploren, dafür bin ich immer 😉
