### ISSUE TITLE
Spielesammlung 

### ISSUE THREAD

**Issue by Nico1808** [aaronschweig/wwi21seb#2]
## Projektidee
Die Idee ist es eine Webseite zu bauen, auf welcher man zwischen mehreren Minigames wählen kann. Wir planen erst einmal die Main Page und 2 sample Spiele zu machen und haben danach dann die Freiheit unsere Webseite um beliebig viele Spiele zu ergänzen. Es soll User geben, welche diverse Spielerdaten wie einen Namen und Highscores speichern. 

**Geplante Features**

- [X] Authentication
- [X] Datenbank
- [X] Server Side Rendering
- [X] (eigene Anwendungspezifische Features der Applikation)
- User registrierung
- User Login
- Speichern von Highscores der korrespondierenden Spiele
- Allg. Speichern von Userdaten in DB

**Geplante Spiele**
- SpaceInvaders
- Snake
- Wordle
- Eine Art Quizduell (vorerst nur ein "Quiz" am Tag, für alle Spieler global (Anschließend evtl. auch 1v1 modus))
- Flappy Bird

Wir planen vorerst alles mit Svelte und SvelteKit umzusetzen. Evtl. folgt eine Auslagerung auf ein externes Backend, wenn benötigt/gewollt. Auf die Datenbanktechnologie haben wir uns noch nicht festgelegt

## Gruppenmitglieder (5-6 Studierende)

@abramsmax
@NilsAbels
@pbahde
@BraunJonas
@MarceloEito
@Nico1808

**Comment by aaronschweig** [comment]
Hi,
danke schonmal für die Zusammenfassung - das ganze sieht für mich soweit gut aus!

Ich weiß nicht, ob ihr das schon gelesen habt, aber durch SvelteKit habt ihr auch die Möglichkeit [API-Routes](https://learn.svelte.dev/tutorial/get-handlers) zu nutzen, solltet ihr einen Use-Case für eine "separate" API haben. Dann müsst ihr nicht so viel Code maintainen und könnt trotzdem alle benefits einer API falls benötigt haben!
